# Smsapi SDK canary sweep (generated by @voxgig/sdkgen).
#
# Every credential slot holds a distinctive value, every diagnostic feature
# this SDK ships is switched on with a capturing sink, a real operation runs
# through every outcome, and every string that leaves the SDK is searched for
# the canaries and their encoded forms. It also proves its own sensitivity:
# with clean switched off the canary MUST show.
#
# A struct node inspects as a handle, so the SDK's own records (the error's
# result and spec, the explain record, every sink record, the context's
# to_data) are also read through the struct JSON; a raw client, entity or
# context node is not, since that is a dump of the heap rather than a
# serialisation the SDK performs.

defmodule Smsapi.CleanTest do
  use ExUnit.Case

  alias Voxgig.Struct, as: S
  alias Smsapi.Helpers, as: H
  alias Smsapi.FeatureHarness, as: FH

  # Generated: the credential's wire placement is fixed when the SDK is built.
  @auth %{suppressed: false, where: "header",
          name: "authorization", basic: false}

  @canary %{
    apikey: "CANARY-APIKEY-k9x2m7q4p1",
    secret: "CANARY-SECRET-w3e8r5t2y6",
    header: "CANARY-HEADER-z1x4c7v0b3",
    value: "CANARY-VALUE-n5m8b2v9c4"
  }

  @mask "[redacted]"

  # Every form a canary can travel in.
  defp forms_of do
    Enum.flat_map(Map.values(@canary), fn v -> [v, Base.encode64(v), S.escurl(v)] end) ++
      [Base.encode64(@canary.apikey <> ":" <> @canary.secret)]
  end

  defp leaks(text), do: Enum.filter(forms_of(), &String.contains?(text, &1))

  # Header maps keep the caller's spelling; the assertion should not care.
  defp header(m, name) do
    if S.ismap(m) do
      Enum.find_value(H.entries(m), fn {k, v} ->
        if String.downcase(to_string(k)) == String.downcase(name), do: v
      end)
    end
  end

  defp push(name, kind, f) do
    try do
      [%{name: name <> ":" <> kind, text: to_string(f.())}]
    rescue
      _ -> []
    catch
      _, _ -> []
    end
  end

  # Every default print of a value, as a sink each.
  defp forms(name, val) do
    push(name, "inspect", fn -> inspect(val, limit: :infinity, printable_limit: :infinity) end) ++
      push(name, "raw", fn -> inspect(val, structs: false, limit: :infinity, printable_limit: :infinity) end) ++
      if is_exception(val) do
        push(name, "message", fn -> Exception.message(val) end) ++
          push(name, "format", fn -> Exception.format(:error, val) end) ++
          push(name, "json", fn -> S.jsonify(val) end)
      else
        []
      end
  end

  # The SDK's own data, through the struct JSON as well.
  defp data_forms(name, node) do
    forms(name, node) ++
      push(name, "json", fn -> S.jsonify(node) end) ++
      push(name, "stringify", fn -> S.stringify(node) end)
  end

  defp error_forms(e) do
    forms("error", e) ++
      if match?(%Smsapi.Error{}, e) do
        data_forms("error.result", e.result) ++ data_forms("error.spec", e.spec)
      else
        []
      end
  end

  defp result_forms(out) do
    cond do
      S.ismap(out) and S.getprop(out, "_client") != nil ->
        forms("result", out) ++ data_forms("result.data", S.getprop(out, "_data"))

      S.islist(out) ->
        forms("result", out)

      true ->
        data_forms("result", out)
    end
  end

  defp add(sinks, items), do: Enum.each(items, fn s -> S.setprop(sinks, S.size(sinks), s) end)
  defp sink_list(sinks), do: Enum.map(H.entries(sinks), &elem(&1, 1))

  # Captures the serialised context from inside the pipeline: what a hook
  # author would hand to a logger.
  defp capture_feature(sinks) do
    cap = fn hook ->
      fn ctx ->
        add(sinks, forms("ctx@" <> hook, ctx))
        add(sinks, data_forms("ctxdata@" <> hook, Smsapi.Context.to_data(ctx)))
        nil
      end
    end

    S.jm([
      "name", "capture", "version", "0.0.1", "active", true, "options", S.jm([]),
      "init", fn _ctx, _opts -> nil end,
      "PreRequest", cap.("PreRequest"),
      "PreResponse", cap.("PreResponse"),
      "PreUnexpected", cap.("PreUnexpected")
    ])
  end

  defp response(status, data, headers) do
    h = S.jm(["content-type", "application/json"])
    Enum.each(headers, fn {k, v} -> S.setprop(h, k, v) end)

    S.jm([
      "status", status,
      "statusText", if(status < 400, do: "OK", else: "ERR"),
      "headers", h,
      "body", S.jsonify(data),
      "json", fn -> data end
    ])
  end

  defp scenarios do
    [
      {"ok",
       fn _url, _fd ->
         {response(200, S.jm(["id", "i1", "name", "n1"]), [{"x-session-token", "RESP-TOKEN-a1b2c3d4e5"}]), nil}
       end},
      {"notfound", fn _url, _fd -> {response(404, S.jm(["error", "no such record"]), []), nil} end},
      {"server", fn _url, _fd -> {response(500, S.jm(["error", "boom"]), []), nil} end},
      {"transport",
       fn url, _fd ->
         {nil, Smsapi.Error.new("transport", "socket hang up (URL was: \"" <> url <> "\")")}
       end},
      {"notjson",
       fn _url, _fd ->
         {S.jm([
            "status", 200, "statusText", "OK", "headers", S.jm([]), "body", "<html>",
            "json", fn -> raise "Unexpected token < in JSON" end
          ]), nil}
       end}
    ]
  end

  defp make_sdk(respond, sinks, cleanopts, extra \\ []) do
    capture = fn name -> fn rec -> add(sinks, data_forms(name, rec)) end end
    feature = S.jm([])

    on = fn name, kvs ->
      if FH.has_feature(name), do: S.setprop(feature, name, S.jm(["active", true] ++ kvs))
    end

    on.("log", ["logger", capture.("log")])
    on.("debug", ["onEntry", capture.("debug")])
    on.("audit", ["sink", capture.("audit")])
    on.("telemetry", ["exporter", capture.("telemetry")])
    on.("cost", ["sink", capture.("cost")])
    on.("metrics", [])
    on.("clienttrack", [])

    clean = S.jm(["values", @canary.value])
    Enum.each(cleanopts, fn {k, v} -> S.setprop(clean, k, v) end)

    Smsapi.new(
      S.jm([
        "apikey", @canary.apikey,
        "secret", @canary.secret,
        "headers", S.jm(["X-Custom-Token", @canary.header]),
        "clean", clean,
        "feature", feature,
        "extend", S.jt([capture_feature(sinks) | extra]),
        "utility", S.jm(["fetcher", fn _ctx, url, fd -> respond.(url, fd) end])
      ])
    )
  end

  # A fresh struct node of the match, since an operation may keep what it is
  # given.
  defp args(match), do: S.jm(Enum.flat_map(match, fn {k, v} -> [k, v] end))

  # The operations this SDK generated, read ops first.
  defp candidates do
    [
      {"available.list", fn sdk -> Smsapi.available(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Available.list(ent, args(match), ctrl) end,
       []},
      {"callback.list", fn sdk -> Smsapi.callback(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Callback.list(ent, args(match), ctrl) end,
       []},
      {"contact.list", fn sdk -> Smsapi.contact(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Contact.list(ent, args(match), ctrl) end,
       ["id"]},
      {"contacts_field.list", fn sdk -> Smsapi.contacts_field(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.ContactsField.list(ent, args(match), ctrl) end,
       []},
      {"contacts_field_option.list", fn sdk -> Smsapi.contacts_field_option(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.ContactsFieldOption.list(ent, args(match), ctrl) end,
       ["field_id"]},
      {"contactsgroup.list", fn sdk -> Smsapi.contactsgroup(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Contactsgroup.list(ent, args(match), ctrl) end,
       ["group_id"]},
      {"field_available.list", fn sdk -> Smsapi.field_available(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.FieldAvailable.list(ent, args(match), ctrl) end,
       []},
      {"opt_out.list", fn sdk -> Smsapi.opt_out(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.OptOut.list(ent, args(match), ctrl) end,
       []},
      {"ping.list", fn sdk -> Smsapi.ping(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Ping.list(ent, args(match), ctrl) end,
       []},
      {"profile.list", fn sdk -> Smsapi.profile(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Profile.list(ent, args(match), ctrl) end,
       []},
      {"rcs.list", fn sdk -> Smsapi.rcs(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Rcs.list(ent, args(match), ctrl) end,
       []},
      {"sendername.list", fn sdk -> Smsapi.sendername(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Sendername.list(ent, args(match), ctrl) end,
       []},
      {"sendername_statement.list", fn sdk -> Smsapi.sendername_statement(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.SendernameStatement.list(ent, args(match), ctrl) end,
       []},
      {"shipment_country_volume.list", fn sdk -> Smsapi.shipment_country_volume(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.ShipmentCountryVolume.list(ent, args(match), ctrl) end,
       []},
      {"short_url.list", fn sdk -> Smsapi.short_url(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.ShortUrl.list(ent, args(match), ctrl) end,
       []},
      {"subuser.list", fn sdk -> Smsapi.subuser(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Subuser.list(ent, args(match), ctrl) end,
       ["id"]},
      {"template.list", fn sdk -> Smsapi.template(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Template.list(ent, args(match), ctrl) end,
       []},
      {"user_rcs_sender_collection.list", fn sdk -> Smsapi.user_rcs_sender_collection(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.UserRcsSenderCollection.list(ent, args(match), ctrl) end,
       []},
      {"blacklist.load", fn sdk -> Smsapi.blacklist(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Blacklist.load(ent, args(match), ctrl) end,
       []},
      {"callback.load", fn sdk -> Smsapi.callback(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Callback.load(ent, args(match), ctrl) end,
       ["id"]},
      {"contact.load", fn sdk -> Smsapi.contact(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Contact.load(ent, args(match), ctrl) end,
       ["contact_id", "group_id", "id"]},
      {"group.load", fn sdk -> Smsapi.group(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Group.load(ent, args(match), ctrl) end,
       ["id"]},
      {"opt_out_setting.load", fn sdk -> Smsapi.opt_out_setting(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.OptOutSetting.load(ent, args(match), ctrl) end,
       []},
      {"permission.load", fn sdk -> Smsapi.permission(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Permission.load(ent, args(match), ctrl) end,
       ["group_id", "id"]},
      {"profile.load", fn sdk -> Smsapi.profile(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Profile.load(ent, args(match), ctrl) end,
       []},
      {"sendername.load", fn sdk -> Smsapi.sendername(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Sendername.load(ent, args(match), ctrl) end,
       ["id"]},
      {"short_url.load", fn sdk -> Smsapi.short_url(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.ShortUrl.load(ent, args(match), ctrl) end,
       ["id"]},
      {"subuser.load", fn sdk -> Smsapi.subuser(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Subuser.load(ent, args(match), ctrl) end,
       ["id"]},
      {"template.load", fn sdk -> Smsapi.template(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Template.load(ent, args(match), ctrl) end,
       ["id"]},
      {"blacklist.create", fn sdk -> Smsapi.blacklist(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Blacklist.create(ent, args(match), ctrl) end,
       []},
      {"blacklist.remove", fn sdk -> Smsapi.blacklist(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Blacklist.remove(ent, args(match), ctrl) end,
       ["id"]},
      {"callback.create", fn sdk -> Smsapi.callback(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Callback.create(ent, args(match), ctrl) end,
       []},
      {"callback.remove", fn sdk -> Smsapi.callback(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Callback.remove(ent, args(match), ctrl) end,
       ["id"]},
      {"callback.update", fn sdk -> Smsapi.callback(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Callback.update(ent, args(match), ctrl) end,
       ["id"]},
      {"contact.create", fn sdk -> Smsapi.contact(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Contact.create(ent, args(match), ctrl) end,
       ["id"]},
      {"contact.remove", fn sdk -> Smsapi.contact(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Contact.remove(ent, args(match), ctrl) end,
       ["group_id", "id"]},
      {"contact.update", fn sdk -> Smsapi.contact(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Contact.update(ent, args(match), ctrl) end,
       ["contact_id", "group_id", "id"]},
      {"contacts_field.create", fn sdk -> Smsapi.contacts_field(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.ContactsField.create(ent, args(match), ctrl) end,
       []},
      {"contacts_field.remove", fn sdk -> Smsapi.contacts_field(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.ContactsField.remove(ent, args(match), ctrl) end,
       ["id"]},
      {"contacts_field.update", fn sdk -> Smsapi.contacts_field(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.ContactsField.update(ent, args(match), ctrl) end,
       ["id"]},
      {"contactsgroup.create", fn sdk -> Smsapi.contactsgroup(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Contactsgroup.create(ent, args(match), ctrl) end,
       ["group_id"]},
      {"contactsgroup.remove", fn sdk -> Smsapi.contactsgroup(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Contactsgroup.remove(ent, args(match), ctrl) end,
       ["contact_id", "group_id", "username"]},
      {"contactsgroup.update", fn sdk -> Smsapi.contactsgroup(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Contactsgroup.update(ent, args(match), ctrl) end,
       ["group_id", "username"]},
      {"contactstrash.remove", fn sdk -> Smsapi.contactstrash(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Contactstrash.remove(ent, args(match), ctrl) end,
       []},
      {"contactstrash.update", fn sdk -> Smsapi.contactstrash(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Contactstrash.update(ent, args(match), ctrl) end,
       []},
      {"group.update", fn sdk -> Smsapi.group(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Group.update(ent, args(match), ctrl) end,
       ["id"]},
      {"mfa_code.create", fn sdk -> Smsapi.mfa_code(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.MfaCode.create(ent, args(match), ctrl) end,
       []},
      {"opt_out.remove", fn sdk -> Smsapi.opt_out(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.OptOut.remove(ent, args(match), ctrl) end,
       ["id"]},
      {"opt_out_setting.update", fn sdk -> Smsapi.opt_out_setting(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.OptOutSetting.update(ent, args(match), ctrl) end,
       []},
      {"permission.create", fn sdk -> Smsapi.permission(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Permission.create(ent, args(match), ctrl) end,
       ["group_id"]},
      {"sendername.create", fn sdk -> Smsapi.sendername(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Sendername.create(ent, args(match), ctrl) end,
       []},
      {"sent_rcs_message.create", fn sdk -> Smsapi.sent_rcs_message(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.SentRcsMessage.create(ent, args(match), ctrl) end,
       []},
      {"short_url.create", fn sdk -> Smsapi.short_url(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.ShortUrl.create(ent, args(match), ctrl) end,
       []},
      {"short_url.remove", fn sdk -> Smsapi.short_url(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.ShortUrl.remove(ent, args(match), ctrl) end,
       ["id"]},
      {"short_url.update", fn sdk -> Smsapi.short_url(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.ShortUrl.update(ent, args(match), ctrl) end,
       ["id"]},
      {"smsdo.create", fn sdk -> Smsapi.smsdo(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Smsdo.create(ent, args(match), ctrl) end,
       []},
      {"smssendername.create", fn sdk -> Smsapi.smssendername(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Smssendername.create(ent, args(match), ctrl) end,
       ["sendername_id"]},
      {"smssendername.remove", fn sdk -> Smsapi.smssendername(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Smssendername.remove(ent, args(match), ctrl) end,
       ["sender"]},
      {"smstemplate.remove", fn sdk -> Smsapi.smstemplate(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Smstemplate.remove(ent, args(match), ctrl) end,
       ["id"]},
      {"subuser.create", fn sdk -> Smsapi.subuser(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Subuser.create(ent, args(match), ctrl) end,
       []},
      {"subuser.remove", fn sdk -> Smsapi.subuser(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Subuser.remove(ent, args(match), ctrl) end,
       ["id"]},
      {"subuser.update", fn sdk -> Smsapi.subuser(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Subuser.update(ent, args(match), ctrl) end,
       ["id"]},
      {"template.create", fn sdk -> Smsapi.template(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Template.create(ent, args(match), ctrl) end,
       []},
      {"template.update", fn sdk -> Smsapi.template(sdk) end,
       fn ent, match, ctrl -> Smsapi.Entity.Template.update(ent, args(match), ctrl) end,
       ["id"]}
    ]
  end

  # The first operation that completes against a plain 200: with no
  # arguments, else with every path parameter its points declare filled in.
  defp usable_op do
    plain =
      Smsapi.new(
        S.jm([
          "apikey", @canary.apikey,
          "utility", S.jm(["fetcher", fn _c, _u, _f -> {response(200, S.jm(["id", "i1"]), []), nil} end])
        ])
      )

    Enum.find_value(candidates(), fn {name, acc, op, params} ->
      filled = Map.new(params, fn p -> {p, "p1"} end)

      Enum.find_value([%{}, filled], fn match ->
        try do
          op.(acc.(plain), match, S.jm([]))
          {name, acc, op, match}
        rescue
          _ -> nil
        catch
          _, _ -> nil
        end
      end)
    end)
  end

  # A feature that raises from inside the pipeline, quoting the request it
  # saw: an error make_error never handled.
  defp throw_feature(unexpected) do
    saw = fn ctx -> "hook saw " <> S.jsonify(S.getprop(ctx, "spec")) end

    S.jm([
      "name", "throwhook", "version", "0.0.1", "active", true, "options", S.jm([]),
      "init", fn _ctx, _opts -> nil end,
      "PreResponse", fn ctx -> raise saw.(ctx) end,
      # Fired from the operation's rescue, before its cleaning.
      "PreUnexpected", fn ctx -> if unexpected, do: raise(saw.(ctx)) end
    ])
  end

  # A stream that fails while the caller iterates it, quoting a credential.
  defp stream_feature do
    S.jm([
      "name", "streamthrow", "version", "0.0.1", "active", true, "options", S.jm([]),
      "init", fn _ctx, _opts -> nil end,
      "PreDone", fn ctx ->
        S.setprop(S.getprop(ctx, "result"), "stream",
          fn -> Stream.map([1], fn _ -> raise "stream saw " <> @canary.apikey end) end)
      end
    ])
  end

  # A stream that succeeds, yielding the result's items.
  defp stream_ok_feature do
    S.jm([
      "name", "streamok", "version", "0.0.1", "active", true, "options", S.jm([]),
      "init", fn _ctx, _opts -> nil end,
      "PreDone", fn ctx ->
        result = S.getprop(ctx, "result")
        rd = S.getprop(result, "resdata")
        items = if S.islist(rd), do: Enum.map(H.entries(rd), &elem(&1, 1)), else: List.wrap(rd)
        S.setprop(result, "stream", fn -> items end)
      end
    ])
  end

  # The target operation, streamed through its entity.
  defp stream_of(sdk, {name, acc, _op, match}, callopts) do
    ent = acc.(sdk)
    mod = S.getprop(ent, "_module")
    mod.stream(ent, List.last(String.split(name, ".")), S.jm(["reqmatch", args(match)]), callopts)
  end

  # Features that fail the operation with the SDK's own error, whose code
  # quotes a registered value: one refuses it as rbac does, and records the
  # error PreUnexpected hands a hook; the other raises.
  defp deny_feature(sinks) do
    S.jm([
      "name", "denyhook", "version", "0.0.1", "active", true, "options", S.jm([]),
      "init", fn _ctx, _opts -> nil end,
      "PrePoint", fn ctx ->
        err = Smsapi.Context.make_error(ctx, "denied:" <> @canary.value, "denied")
        S.setprop(S.getprop(ctx, "out"), "point", err)
      end,
      "PreUnexpected", fn ctx ->
        add(sinks, error_forms(S.getprop(S.getprop(ctx, "ctrl"), "err")))
        nil
      end
    ])
  end

  defp raise_feature do
    S.jm([
      "name", "raisehook", "version", "0.0.1", "active", true, "options", S.jm([]),
      "init", fn _ctx, _opts -> nil end,
      "PreResponse", fn _ctx -> raise Smsapi.Error.new("raised:" <> @canary.value, "raised") end
    ])
  end

  defp drive(sdk, {_name, acc, op, match}, ctrl, sinks) do
    ent = acc.(sdk)
    # A caller may keep the record it passed rather than read ctrl.explain.
    held = S.getprop(ctrl, "explain")

    {out, err} =
      try do
        {op.(ent, match, ctrl), nil}
      rescue
        e -> {nil, e}
      end

    if err != nil, do: add(sinks, error_forms(err))
    if out != nil, do: add(sinks, result_forms(out))
    explain = S.getprop(ctrl, "explain")
    if explain != nil, do: add(sinks, data_forms("explain", explain))
    if held != nil and held != explain, do: add(sinks, data_forms("explain:held", held))
    err
  end

  @no_target "no operation of this SDK completes against a plain 200; nothing to sweep"

  # ExUnit has no runtime skip, so a sweep with nothing to drive says so.
  test "no credential leaves the SDK in any form" do
    case usable_op() do
      nil -> IO.puts("SKIP no credential leaves the SDK in any form: " <> @no_target)
      target -> sweep(target)
    end
  end

  test "the sweep can see a leak: clean switched off shows the credential" do
    case usable_op() do
      nil -> IO.puts("SKIP the sweep can see a leak: " <> @no_target)
      target -> sweep_blind(target)
    end
  end

  defp sweep(target) do
    sinks = S.jt([])

    variants = [
      {"throw", fn -> S.jm([]) end},
      {"explain", fn -> S.jm(["explain", S.jm([])]) end},
      {"nothrow", fn -> S.jm(["throw", false, "explain", S.jm([])]) end}
    ]

    {errors, explains} =
      Enum.reduce(scenarios(), {%{}, %{}}, fn {sname, respond}, acc ->
        Enum.reduce(variants, acc, fn {vname, mkctrl}, {errors, explains} ->
          sdk = make_sdk(respond, sinks, [])
          ctrl = mkctrl.()
          err = drive(sdk, target, ctrl, sinks)
          add(sinks, forms("sdk", sdk))
          key = sname <> "/" <> vname
          errors = if err != nil, do: Map.put(errors, key, err), else: errors
          ex = S.getprop(ctrl, "explain")
          explains = if ex != nil, do: Map.put(explains, key, ex), else: explains
          {errors, explains}
        end)
      end)

    # A credential mistyped as a map is rejected by validation, whose message
    # quotes the value it rejected.
    rejected =
      try do
        Smsapi.new(S.jm(["apikey", S.jm(["value", @canary.apikey]), "clean", S.jm(["values", @canary.value])]))
        nil
      rescue
        e -> e
      end

    assert rejected != nil, "a credential mistyped as a map should be rejected"
    add(sinks, forms("rejected", rejected))

    # An error a feature hook raises, quoting the request, skips make_error.
    [{_name, ok} | _] = scenarios()

    for unexpected <- [false, true] do
      hooked = make_sdk(ok, sinks, [], [throw_feature(unexpected)])
      err = drive(hooked, target, S.jm(["explain", S.jm([])]), sinks)
      assert err != nil, "the throwing hook should fail the operation"
    end

    # Iterating a stream runs through the same cleaning path as the operation,
    # and the explain record the caller passed is cleaned however it ends.
    for {name, extra} <- [{"stream", [stream_feature()]}, {"stream-ok", [stream_ok_feature()]}, {"stream-plain", []}] do
      explain = S.jm([])
      callopts = S.jm(["ctrl", S.jm(["explain", explain])])

      streamerr =
        try do
          Enum.to_list(stream_of(make_sdk(ok, sinks, [], extra), target, callopts))
          nil
        rescue
          e -> e
        end

      assert (name == "stream") == (streamerr != nil), name <> ": only the failing stream raises"
      if streamerr != nil, do: add(sinks, forms(name, streamerr))
      assert S.size(explain) > 0, name <> ": the explain record was not filled"
      add(sinks, data_forms(name <> ":explain", explain))
    end

    # A feature's own error keeps its code, which is cleaned like the message:
    # returned, handed to a hook, raised by a hook, and nested in a record.
    denied = drive(make_sdk(ok, sinks, [], [deny_feature(sinks)]), target, S.jm([]), sinks)
    assert denied != nil, "the refusing hook should fail the operation"
    raised = drive(make_sdk(ok, sinks, [], [raise_feature()]), target, S.jm([]), sinks)
    assert raised != nil, "the raising hook should fail the operation"

    nested =
      Smsapi.Utility.clean_impl(Smsapi.get_root_ctx(make_sdk(ok, sinks, [])),
        S.jm(["err", Smsapi.Error.new("nested:" <> @canary.value, "nested")]))

    add(sinks, data_forms("nested", nested))

    # A client given no clean block at all masks by the schema defaults.
    [_ok, {_nf, notfound_respond} | _] = scenarios()

    bare =
      Smsapi.new(
        S.jm([
          "apikey", @canary.apikey,
          "secret", @canary.secret,
          "headers", S.jm(["X-Custom-Token", @canary.header]),
          "utility", S.jm(["fetcher", fn _ctx, url, fd -> notfound_respond.(url, fd) end])
        ])
      )

    barerr = drive(bare, target, S.jm([]), sinks)
    assert barerr != nil, "the 404 scenario must fail without a clean block"

    # The raw path returns its failure rather than raising it.
    [_ok, _nf, _server, {_tr, transport_respond} | _] = scenarios()
    direct = Smsapi.direct(make_sdk(transport_respond, sinks, []), S.jm(["path", "raw"]))
    assert S.getprop(direct, "ok") == false, "a transport failure should fail direct()"
    add(sinks, forms("direct", S.getprop(direct, "err")))

    all = sink_list(sinks)
    leaked = Enum.filter(all, fn s -> leaks(s.text) != [] end)

    IO.puts("clean: swept #{length(all)} surface(s), #{length(leaked)} leak(s)")

    assert leaked == [],
           "credential leaked through: " <>
             Enum.map_join(leaked, "; ", fn s -> s.name <> " [" <> Enum.join(leaks(s.text), ", ") <> "]" end)

    # The positive half: the slot the credential travelled in is masked, and
    # an unregistered token in a response header is masked by name.
    notfound = errors["notfound/throw"]
    assert notfound != nil, "the 404 scenario must throw"
    assert match?(%Smsapi.Error{}, notfound), "the 404 error is an SDK error"
    assert Smsapi.Error.status(notfound) == 404
    spec = notfound.spec

    unless @auth.suppressed do
      case @auth.where do
        "query" ->
          assert header(S.getprop(spec, "query"), @auth.name) == @mask

        "cookie" ->
          assert String.contains?(to_string(header(S.getprop(spec, "headers"), "cookie")), @mask)

        _ ->
          assert String.ends_with?(to_string(header(S.getprop(spec, "headers"), @auth.name)), @mask)
      end
    end

    assert header(S.getprop(spec, "headers"), "x-custom-token") == @mask
    assert denied.code == "denied:" <> @mask
    assert raised.code == "raised:" <> @mask
    assert S.getpath(nested, "err.code") == "nested:" <> @mask
    assert header(S.getprop(barerr.spec, "headers"), "x-custom-token") == @mask

    explained = explains["ok/explain"]
    result = if explained != nil, do: S.getprop(explained, "result"), else: nil
    assert S.ismap(result), "the explain record should carry the result"
    assert header(S.getprop(result, "headers"), "x-session-token") == @mask
  end

  defp sweep_blind(target) do
    sinks = S.jt([])
    [_ok, {_name, notfound} | _] = scenarios()
    sdk = make_sdk(notfound, sinks, [{"active", false}])
    err = drive(sdk, target, S.jm([]), sinks)
    assert err != nil

    # Explaining a failure must not cost it its error.
    explained =
      drive(make_sdk(notfound, S.jt([]), [{"active", false}]), target, S.jm(["explain", S.jm([])]), S.jt([]))

    assert explained != nil and Exception.message(explained) == Exception.message(err),
           "with clean off, explain lost the error"

    assert Enum.any?(sink_list(sinks), fn s -> leaks(s.text) != [] end),
           "with clean off, nothing showed the canary: the sweep is blind"

    unless @auth.suppressed do
      text = S.jsonify(err.spec)

      assert String.contains?(text, @canary.apikey) or
               String.contains?(text, Base.encode64(@canary.apikey <> ":" <> @canary.secret)),
             "the raw spec should carry the credential when clean is off"
    end
  end

  test "a registered value used as a property name is masked, collisions kept" do
    cfg = Smsapi.Utility.make_clean_config(S.jm(["keys", "key,secret,token"]))
    ctx = S.jm(["options", S.jm(["__derived__", S.jm(["clean", cfg])])])
    Smsapi.Utility.clean_add_impl(ctx, "ZZVAL-abc123")
    Smsapi.Utility.clean_add_impl(ctx, "ZZVAL-xyz789")
    out = Smsapi.Utility.clean_impl(ctx, S.jm(["ZZVAL-abc123", 1, "ZZVAL-xyz789", 2, "plain", 3]))
    assert S.getprop(out, @mask) == 1
    assert S.getprop(out, @mask <> "#1") == 2
    assert S.getprop(out, "plain") == 3
    assert "ZZVAL-abc123" not in S.keysof(out)
  end

  # A feature's name is not a field name: a feature called secrets does not
  # make its settings secret, though a sensitive field inside it still is. An
  # entity block, of entity settings or seeded records, is not read at all.
  test "a feature's name is read as a name" do
    record = S.jm(["zztoken", S.jm(["ZZTOKEN01", S.jm(["note", "PLAINRECORD-t5r3e1w9"])])])

    client =
      Smsapi.new(
        S.jm([
          "apikey", @canary.apikey,
          "feature",
          S.jm([
            "secrets", S.jm(["active", false, "name", "ZZNAME-feat123", "token", "ZZTOKEN-feat456"]),
            "test", S.jm(["active", false, "entity", record])
          ]),
          "entity", S.jm(["zztoken", S.jm(["alias", S.jm(["zzkey", "PLAINALIAS-m2n4b6v8"])])])
        ])
      )

    ctx = Smsapi.get_root_ctx(client)
    assert Smsapi.Utility.clean_impl(ctx, "ZZNAME-feat123 ZZTOKEN-feat456") == "ZZNAME-feat123 " <> @mask
    assert Smsapi.Utility.clean_impl(ctx, "record PLAINRECORD-t5r3e1w9") == "record PLAINRECORD-t5r3e1w9"
    assert Smsapi.Utility.clean_impl(ctx, "alias PLAINALIAS-m2n4b6v8") == "alias PLAINALIAS-m2n4b6v8"
  end

  test "the generated config's own clean block is honoured" do
    config = S.jm(["options", S.jm(["clean", S.jm(["keys", "zzsens", "values", "CONFIG-SEEDED-1"])])])
    ctx = S.jm(["config", config, "options", S.jm(["clean", S.jm(["values", "CALLER-SEEDED-2"])])])
    cctx = S.jm(["options", Smsapi.Utility.make_options_impl(ctx)])

    assert Smsapi.Utility.clean_impl(cctx, "a CONFIG-SEEDED-1 b CALLER-SEEDED-2") ==
             "a " <> @mask <> " b " <> @mask

    out = Smsapi.Utility.clean_impl(cctx, S.jm(["my_zzsens", "x", "other", "y"]))
    assert S.getprop(out, "my_zzsens") == @mask
    assert S.getprop(out, "other") == "y"
    assert S.getpath(config, "options.clean.keys") == "zzsens"
    assert S.getpath(config, "options.clean.values") == "CONFIG-SEEDED-1"
  end

  test "clean_add_sensitive registers every scalar under a sensitive name, at any depth" do
    cfg = Smsapi.Utility.make_clean_config(S.jm(["keys", "key,secret,token"]))
    ctx = S.jm(["options", S.jm(["__derived__", S.jm(["clean", cfg])])])

    Smsapi.Utility.clean_add_sensitive(ctx, S.jm([
      "apikey", S.jm(["value", "NESTED-SECRET-1"]),
      "headers", S.jm(["X-Api-Token", S.jt(["LISTED-SECRET-2"])]),
      "secret", 123456789,
      "name", "not-a-secret"
    ]))

    values = Enum.map(H.entries(S.getprop(cfg, "values")), &elem(&1, 1))
    assert "NESTED-SECRET-1" in values
    assert "LISTED-SECRET-2" in values
    assert "123456789" in values
    refute "not-a-secret" in values
  end
end
