# smsapi data — generated entity accessors.
#
# GENERATED by @voxgig/sdkgen (py-data target). Edits are overwritten.
#
# One accessor per entity. Column names and dtypes come from the API model,
# so `ad.<tab>` and `ad.thing?` replace a trip to the reference docs.

from __future__ import annotations

import pandas as pd

from .fetch import drain, MAX_PAGES_DEFAULT
from .frames import build_frame, to_series, FLATTEN_DEFAULT


class EntityFrames:
    """Mixin carrying the generated accessors. Mixed into <Name>Data."""

    _ACCESSORS = [
        "availables",
        "callbacks",
        "contacts",
        "contacts_fields",
        "contacts_field_options",
        "contactsgroups",
        "field_availables",
        "opt_outs",
        "pings",
        "profiles",
        "rcs",
        "sendernames",
        "sendername_statements",
        "shipment_country_volumes",
        "short_urls",
        "subusers",
        "templates",
        "user_rcs_sender_collections",
        "callback",
        "contact",
        "group",
        "permission",
        "sendername",
        "short_url",
        "subuser",
        "template",
    ]

    def availables(
        self,
        *,
        limit: int | None = None,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
        max_pages: int = MAX_PAGES_DEFAULT,
        quiet: bool = False,
        **match,
    ) -> pd.DataFrame:
        """All available records as a DataFrame.

        Columns:
          name (string)
          normalize (boolean)
          template (string)

        Every page is fetched by default. Pass limit= for a slice.
        Keyword arguments not named above are passed to the API as filters.
        """
        ent = self.sdk.Available()
        rows = drain(
            lambda ctrl: ent.list(match or None, ctrl or None),
            self.sdk,
            limit=limit,
            max_pages=max_pages,
            quiet=quiet,
        )
        return build_frame(
            rows,
            dtypes={
                "name": "string",
                "normalize": "boolean",
                "template": "string",
            },
            order=[
                "name",
                "normalize",
                "template",
            ],
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def callbacks(
        self,
        *,
        limit: int | None = None,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
        max_pages: int = MAX_PAGES_DEFAULT,
        quiet: bool = False,
        **match,
    ) -> pd.DataFrame:
        """All callback records as a DataFrame.

        Columns:
          active (boolean)
          api_version (Int64)
          id (string)
          invalid (boolean)
          receiver (object)
          receiver_type (string)
          type (string)
          url (string)

        Every page is fetched by default. Pass limit= for a slice.
        Keyword arguments not named above are passed to the API as filters.
        """
        ent = self.sdk.Callback()
        rows = drain(
            lambda ctrl: ent.list(match or None, ctrl or None),
            self.sdk,
            limit=limit,
            max_pages=max_pages,
            quiet=quiet,
        )
        return build_frame(
            rows,
            dtypes={
                "active": "boolean",
                "api_version": "Int64",
                "id": "string",
                "invalid": "boolean",
                "receiver": "object",
                "receiver_type": "string",
                "type": "string",
                "url": "string",
            },
            order=[
                "active",
                "api_version",
                "id",
                "invalid",
                "receiver",
                "receiver_type",
                "type",
                "url",
            ],
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def contacts(
        self,
        *,
        limit: int | None = None,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
        max_pages: int = MAX_PAGES_DEFAULT,
        quiet: bool = False,
        **match,
    ) -> pd.DataFrame:
        """All contact records as a DataFrame.

        Columns:
          birthday_date (string)
          city (string)
          collection (object, required)
          contact_expire_after (Int64, required)
          contacts_count (Int64, required)
          country (string)
          created_by (string, required)
          date_created (string, required)
          date_updated (string, required)
          description (string)
          email (string)
          first_name (string)
          gender (string, required)
          group_id (string)
          groups (object, required)
          id (string, required)
          idx (string)
          last_name (string)
          name (string, required)
          permissions (object)
          phone_number (string)
          read (boolean)
          send (boolean)
          size (Int64, required)
          … and 5 more (see README.md, or df.dtypes)

        Every page is fetched by default. Pass limit= for a slice.
        Keyword arguments not named above are passed to the API as filters.
        """
        ent = self.sdk.Contact()
        rows = drain(
            lambda ctrl: ent.list(match or None, ctrl or None),
            self.sdk,
            limit=limit,
            max_pages=max_pages,
            quiet=quiet,
        )
        return build_frame(
            rows,
            dtypes={
                "birthday_date": "string",
                "city": "string",
                "collection": "object",
                "contact_expire_after": "Int64",
                "contacts_count": "Int64",
                "country": "string",
                "created_by": "string",
                "date_created": "string",
                "date_updated": "string",
                "description": "string",
                "email": "string",
                "first_name": "string",
                "gender": "string",
                "group_id": "string",
                "groups": "object",
                "id": "string",
                "idx": "string",
                "last_name": "string",
                "name": "string",
                "permissions": "object",
                "phone_number": "string",
                "read": "boolean",
                "send": "boolean",
                "size": "Int64",
                "source": "string",
                "type": "string",
                "username": "string",
                "value": "string",
                "write": "boolean",
            },
            order=[
                "birthday_date",
                "city",
                "collection",
                "contact_expire_after",
                "contacts_count",
                "country",
                "created_by",
                "date_created",
                "date_updated",
                "description",
                "email",
                "first_name",
                "gender",
                "group_id",
                "groups",
                "id",
                "idx",
                "last_name",
                "name",
                "permissions",
                "phone_number",
                "read",
                "send",
                "size",
                "source",
                "type",
                "username",
                "value",
                "write",
            ],
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def contacts_fields(
        self,
        *,
        limit: int | None = None,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
        max_pages: int = MAX_PAGES_DEFAULT,
        quiet: bool = False,
        **match,
    ) -> pd.DataFrame:
        """All contacts_field records as a DataFrame.

        Columns:
          birthday_date (string)
          city (string)
          contact_expire_after (Int64, required)
          contacts_count (Int64)
          country (string)
          created_by (string, required)
          date_created (string, required)
          date_updated (string, required)
          description (string)
          email (string)
          first_name (string)
          gender (string, required)
          group_id (string)
          groups (object, required)
          id (string)
          idx (string)
          last_name (string)
          name (string)
          permissions (object)
          phone_number (string)
          read (boolean)
          send (boolean)
          source (string)
          type (string)
          … and 3 more (see README.md, or df.dtypes)

        Every page is fetched by default. Pass limit= for a slice.
        Keyword arguments not named above are passed to the API as filters.
        """
        ent = self.sdk.ContactsField()
        rows = drain(
            lambda ctrl: ent.list(match or None, ctrl or None),
            self.sdk,
            limit=limit,
            max_pages=max_pages,
            quiet=quiet,
        )
        return build_frame(
            rows,
            dtypes={
                "birthday_date": "string",
                "city": "string",
                "contact_expire_after": "Int64",
                "contacts_count": "Int64",
                "country": "string",
                "created_by": "string",
                "date_created": "string",
                "date_updated": "string",
                "description": "string",
                "email": "string",
                "first_name": "string",
                "gender": "string",
                "group_id": "string",
                "groups": "object",
                "id": "string",
                "idx": "string",
                "last_name": "string",
                "name": "string",
                "permissions": "object",
                "phone_number": "string",
                "read": "boolean",
                "send": "boolean",
                "source": "string",
                "type": "string",
                "username": "string",
                "value": "string",
                "write": "boolean",
            },
            order=[
                "birthday_date",
                "city",
                "contact_expire_after",
                "contacts_count",
                "country",
                "created_by",
                "date_created",
                "date_updated",
                "description",
                "email",
                "first_name",
                "gender",
                "group_id",
                "groups",
                "id",
                "idx",
                "last_name",
                "name",
                "permissions",
                "phone_number",
                "read",
                "send",
                "source",
                "type",
                "username",
                "value",
                "write",
            ],
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def contacts_field_options(
        self,
        *,
        limit: int | None = None,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
        max_pages: int = MAX_PAGES_DEFAULT,
        quiet: bool = False,
        **match,
    ) -> pd.DataFrame:
        """All contacts_field_option records as a DataFrame.

        Columns:
          birthday_date (string)
          city (string)
          contact_expire_after (Int64, required)
          contacts_count (Int64)
          country (string)
          created_by (string, required)
          date_created (string, required)
          date_updated (string, required)
          description (string)
          email (string)
          first_name (string)
          gender (string, required)
          group_id (string)
          groups (object, required)
          id (string, required)
          idx (string)
          last_name (string)
          name (string)
          permissions (object)
          phone_number (string)
          read (boolean)
          send (boolean)
          source (string)
          type (string)
          … and 3 more (see README.md, or df.dtypes)

        Every page is fetched by default. Pass limit= for a slice.
        Keyword arguments not named above are passed to the API as filters.
        """
        ent = self.sdk.ContactsFieldOption()
        rows = drain(
            lambda ctrl: ent.list(match or None, ctrl or None),
            self.sdk,
            limit=limit,
            max_pages=max_pages,
            quiet=quiet,
        )
        return build_frame(
            rows,
            dtypes={
                "birthday_date": "string",
                "city": "string",
                "contact_expire_after": "Int64",
                "contacts_count": "Int64",
                "country": "string",
                "created_by": "string",
                "date_created": "string",
                "date_updated": "string",
                "description": "string",
                "email": "string",
                "first_name": "string",
                "gender": "string",
                "group_id": "string",
                "groups": "object",
                "id": "string",
                "idx": "string",
                "last_name": "string",
                "name": "string",
                "permissions": "object",
                "phone_number": "string",
                "read": "boolean",
                "send": "boolean",
                "source": "string",
                "type": "string",
                "username": "string",
                "value": "string",
                "write": "boolean",
            },
            order=[
                "birthday_date",
                "city",
                "contact_expire_after",
                "contacts_count",
                "country",
                "created_by",
                "date_created",
                "date_updated",
                "description",
                "email",
                "first_name",
                "gender",
                "group_id",
                "groups",
                "id",
                "idx",
                "last_name",
                "name",
                "permissions",
                "phone_number",
                "read",
                "send",
                "source",
                "type",
                "username",
                "value",
                "write",
            ],
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def contactsgroups(
        self,
        *,
        limit: int | None = None,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
        max_pages: int = MAX_PAGES_DEFAULT,
        quiet: bool = False,
        **match,
    ) -> pd.DataFrame:
        """All contactsgroup records as a DataFrame.

        Columns:
          birthday_date (string)
          city (string)
          contact_expire_after (Int64, required)
          contacts_count (Int64)
          country (string)
          created_by (string, required)
          date_created (string, required)
          date_updated (string, required)
          description (string)
          email (string)
          first_name (string)
          gender (string, required)
          group_id (string, required)
          groups (object, required)
          id (string, required)
          idx (string)
          last_name (string)
          name (string)
          permissions (object)
          phone_number (string)
          read (boolean, required)
          send (boolean, required)
          source (string)
          type (string)
          … and 3 more (see README.md, or df.dtypes)

        Every page is fetched by default. Pass limit= for a slice.
        Keyword arguments not named above are passed to the API as filters.
        """
        ent = self.sdk.Contactsgroup()
        rows = drain(
            lambda ctrl: ent.list(match or None, ctrl or None),
            self.sdk,
            limit=limit,
            max_pages=max_pages,
            quiet=quiet,
        )
        return build_frame(
            rows,
            dtypes={
                "birthday_date": "string",
                "city": "string",
                "contact_expire_after": "Int64",
                "contacts_count": "Int64",
                "country": "string",
                "created_by": "string",
                "date_created": "string",
                "date_updated": "string",
                "description": "string",
                "email": "string",
                "first_name": "string",
                "gender": "string",
                "group_id": "string",
                "groups": "object",
                "id": "string",
                "idx": "string",
                "last_name": "string",
                "name": "string",
                "permissions": "object",
                "phone_number": "string",
                "read": "boolean",
                "send": "boolean",
                "source": "string",
                "type": "string",
                "username": "string",
                "value": "string",
                "write": "boolean",
            },
            order=[
                "birthday_date",
                "city",
                "contact_expire_after",
                "contacts_count",
                "country",
                "created_by",
                "date_created",
                "date_updated",
                "description",
                "email",
                "first_name",
                "gender",
                "group_id",
                "groups",
                "id",
                "idx",
                "last_name",
                "name",
                "permissions",
                "phone_number",
                "read",
                "send",
                "source",
                "type",
                "username",
                "value",
                "write",
            ],
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def field_availables(
        self,
        *,
        limit: int | None = None,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
        max_pages: int = MAX_PAGES_DEFAULT,
        quiet: bool = False,
        **match,
    ) -> pd.DataFrame:
        """All field_available records as a DataFrame.

        Columns:
          built_in (boolean)
          id (string)
          name (string)
          options (object)
          type (string)

        Every page is fetched by default. Pass limit= for a slice.
        Keyword arguments not named above are passed to the API as filters.
        """
        ent = self.sdk.FieldAvailable()
        rows = drain(
            lambda ctrl: ent.list(match or None, ctrl or None),
            self.sdk,
            limit=limit,
            max_pages=max_pages,
            quiet=quiet,
        )
        return build_frame(
            rows,
            dtypes={
                "built_in": "boolean",
                "id": "string",
                "name": "string",
                "options": "object",
                "type": "string",
            },
            order=[
                "built_in",
                "id",
                "name",
                "options",
                "type",
            ],
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def opt_outs(
        self,
        *,
        limit: int | None = None,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
        max_pages: int = MAX_PAGES_DEFAULT,
        quiet: bool = False,
        **match,
    ) -> pd.DataFrame:
        """All opt_out records as a DataFrame.

        Columns:
          date (string)
          id (string)
          links (object)
          phoneNumber (Int64)

        Every page is fetched by default. Pass limit= for a slice.
        Keyword arguments not named above are passed to the API as filters.
        """
        ent = self.sdk.OptOut()
        rows = drain(
            lambda ctrl: ent.list(match or None, ctrl or None),
            self.sdk,
            limit=limit,
            max_pages=max_pages,
            quiet=quiet,
        )
        return build_frame(
            rows,
            dtypes={
                "date": "string",
                "id": "string",
                "links": "object",
                "phoneNumber": "Int64",
            },
            order=[
                "date",
                "id",
                "links",
                "phoneNumber",
            ],
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def pings(
        self,
        *,
        limit: int | None = None,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
        max_pages: int = MAX_PAGES_DEFAULT,
        quiet: bool = False,
        **match,
    ) -> pd.DataFrame:
        """All ping records as a DataFrame.

        Columns:
          authorized (boolean, required)
          unavailable (object, required)

        Every page is fetched by default. Pass limit= for a slice.
        Keyword arguments not named above are passed to the API as filters.
        """
        ent = self.sdk.Ping()
        rows = drain(
            lambda ctrl: ent.list(match or None, ctrl or None),
            self.sdk,
            limit=limit,
            max_pages=max_pages,
            quiet=quiet,
        )
        return build_frame(
            rows,
            dtypes={
                "authorized": "boolean",
                "unavailable": "object",
            },
            order=[
                "authorized",
                "unavailable",
            ],
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def profiles(
        self,
        *,
        limit: int | None = None,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
        max_pages: int = MAX_PAGES_DEFAULT,
        quiet: bool = False,
        **match,
    ) -> pd.DataFrame:
        """All profile records as a DataFrame.

        Columns:
          email (string, required)
          name (string, required)
          payment_type (string, required)
          phone_number (Int64, required)
          points (Float64)
          user_type (string, required)
          username (string, required)

        Every page is fetched by default. Pass limit= for a slice.
        Keyword arguments not named above are passed to the API as filters.
        """
        ent = self.sdk.Profile()
        rows = drain(
            lambda ctrl: ent.list(match or None, ctrl or None),
            self.sdk,
            limit=limit,
            max_pages=max_pages,
            quiet=quiet,
        )
        return build_frame(
            rows,
            dtypes={
                "email": "string",
                "name": "string",
                "payment_type": "string",
                "phone_number": "Int64",
                "points": "Float64",
                "user_type": "string",
                "username": "string",
            },
            order=[
                "email",
                "name",
                "payment_type",
                "phone_number",
                "points",
                "user_type",
                "username",
            ],
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def rcs(
        self,
        *,
        limit: int | None = None,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
        max_pages: int = MAX_PAGES_DEFAULT,
        quiet: bool = False,
        **match,
    ) -> pd.DataFrame:
        """All rcs records as a DataFrame.

        No fields are declared for this entity in the API model;
        the frame's columns come from whatever the API returns.

        Every page is fetched by default. Pass limit= for a slice.
        Keyword arguments not named above are passed to the API as filters.
        """
        ent = self.sdk.Rcs()
        rows = drain(
            lambda ctrl: ent.list(match or None, ctrl or None),
            self.sdk,
            limit=limit,
            max_pages=max_pages,
            quiet=quiet,
        )
        return build_frame(
            rows,
            dtypes={},
            order=[],
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def sendernames(
        self,
        *,
        limit: int | None = None,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
        max_pages: int = MAX_PAGES_DEFAULT,
        quiet: bool = False,
        **match,
    ) -> pd.DataFrame:
        """All sendername records as a DataFrame.

        Columns:
          created_at (string)
          id (string)
          is_default (boolean)
          sender (string)
          status (string)

        Every page is fetched by default. Pass limit= for a slice.
        Keyword arguments not named above are passed to the API as filters.
        """
        ent = self.sdk.Sendername()
        rows = drain(
            lambda ctrl: ent.list(match or None, ctrl or None),
            self.sdk,
            limit=limit,
            max_pages=max_pages,
            quiet=quiet,
        )
        return build_frame(
            rows,
            dtypes={
                "created_at": "string",
                "id": "string",
                "is_default": "boolean",
                "sender": "string",
                "status": "string",
            },
            order=[
                "created_at",
                "id",
                "is_default",
                "sender",
                "status",
            ],
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def sendername_statements(
        self,
        *,
        limit: int | None = None,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
        max_pages: int = MAX_PAGES_DEFAULT,
        quiet: bool = False,
        **match,
    ) -> pd.DataFrame:
        """All sendername_statement records as a DataFrame.

        Columns:
          content (string)
          statements (object)
          title (string)

        Every page is fetched by default. Pass limit= for a slice.
        Keyword arguments not named above are passed to the API as filters.
        """
        ent = self.sdk.SendernameStatement()
        rows = drain(
            lambda ctrl: ent.list(match or None, ctrl or None),
            self.sdk,
            limit=limit,
            max_pages=max_pages,
            quiet=quiet,
        )
        return build_frame(
            rows,
            dtypes={
                "content": "string",
                "statements": "object",
                "title": "string",
            },
            order=[
                "content",
                "statements",
                "title",
            ],
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def shipment_country_volumes(
        self,
        *,
        limit: int | None = None,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
        max_pages: int = MAX_PAGES_DEFAULT,
        quiet: bool = False,
        **match,
    ) -> pd.DataFrame:
        """All shipment_country_volume records as a DataFrame.

        Columns:
          country_code (string)
          country_limit (Int64)
          country_name (string)
          usage (Int64)

        Every page is fetched by default. Pass limit= for a slice.
        Keyword arguments not named above are passed to the API as filters.
        """
        ent = self.sdk.ShipmentCountryVolume()
        rows = drain(
            lambda ctrl: ent.list(match or None, ctrl or None),
            self.sdk,
            limit=limit,
            max_pages=max_pages,
            quiet=quiet,
        )
        return build_frame(
            rows,
            dtypes={
                "country_code": "string",
                "country_limit": "Int64",
                "country_name": "string",
                "usage": "Int64",
            },
            order=[
                "country_code",
                "country_limit",
                "country_name",
                "usage",
            ],
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def short_urls(
        self,
        *,
        limit: int | None = None,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
        max_pages: int = MAX_PAGES_DEFAULT,
        quiet: bool = False,
        **match,
    ) -> pd.DataFrame:
        """All short_url records as a DataFrame.

        Columns:
          description (string)
          expire (string)
          filename (string)
          hits (Int64)
          hits_unique (Int64)
          id (string)
          name (string)
          short_url (string)
          type (string)
          url (string)

        Every page is fetched by default. Pass limit= for a slice.
        Keyword arguments not named above are passed to the API as filters.
        """
        ent = self.sdk.ShortUrl()
        rows = drain(
            lambda ctrl: ent.list(match or None, ctrl or None),
            self.sdk,
            limit=limit,
            max_pages=max_pages,
            quiet=quiet,
        )
        return build_frame(
            rows,
            dtypes={
                "description": "string",
                "expire": "string",
                "filename": "string",
                "hits": "Int64",
                "hits_unique": "Int64",
                "id": "string",
                "name": "string",
                "short_url": "string",
                "type": "string",
                "url": "string",
            },
            order=[
                "description",
                "expire",
                "filename",
                "hits",
                "hits_unique",
                "id",
                "name",
                "short_url",
                "type",
                "url",
            ],
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def subusers(
        self,
        *,
        limit: int | None = None,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
        max_pages: int = MAX_PAGES_DEFAULT,
        quiet: bool = False,
        **match,
    ) -> pd.DataFrame:
        """All subuser records as a DataFrame.

        Columns:
          active (boolean)
          credentials (object, required)
          description (string)
          id (string)
          points (object)
          username (string)

        Every page is fetched by default. Pass limit= for a slice.
        Keyword arguments not named above are passed to the API as filters.
        """
        ent = self.sdk.Subuser()
        rows = drain(
            lambda ctrl: ent.list(match or None, ctrl or None),
            self.sdk,
            limit=limit,
            max_pages=max_pages,
            quiet=quiet,
        )
        return build_frame(
            rows,
            dtypes={
                "active": "boolean",
                "credentials": "object",
                "description": "string",
                "id": "string",
                "points": "object",
                "username": "string",
            },
            order=[
                "active",
                "credentials",
                "description",
                "id",
                "points",
                "username",
            ],
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def templates(
        self,
        *,
        limit: int | None = None,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
        max_pages: int = MAX_PAGES_DEFAULT,
        quiet: bool = False,
        **match,
    ) -> pd.DataFrame:
        """All template records as a DataFrame.

        Columns:
          id (string)
          name (string)
          normalize (boolean)
          template (string)

        Every page is fetched by default. Pass limit= for a slice.
        Keyword arguments not named above are passed to the API as filters.
        """
        ent = self.sdk.Template()
        rows = drain(
            lambda ctrl: ent.list(match or None, ctrl or None),
            self.sdk,
            limit=limit,
            max_pages=max_pages,
            quiet=quiet,
        )
        return build_frame(
            rows,
            dtypes={
                "id": "string",
                "name": "string",
                "normalize": "boolean",
                "template": "string",
            },
            order=[
                "id",
                "name",
                "normalize",
                "template",
            ],
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def user_rcs_sender_collections(
        self,
        *,
        limit: int | None = None,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
        max_pages: int = MAX_PAGES_DEFAULT,
        quiet: bool = False,
        **match,
    ) -> pd.DataFrame:
        """All user_rcs_sender_collection records as a DataFrame.

        Columns:
          deliveredAt (string)
          expiredAt (string)
          id (string)
          interface (string)
          messageType (string)
          readAt (string)
          recipient (string)
          sender (string)
          senderId (string)
          sentAt (string)

        Every page is fetched by default. Pass limit= for a slice.
        Keyword arguments not named above are passed to the API as filters.
        """
        ent = self.sdk.UserRcsSenderCollection()
        rows = drain(
            lambda ctrl: ent.list(match or None, ctrl or None),
            self.sdk,
            limit=limit,
            max_pages=max_pages,
            quiet=quiet,
        )
        return build_frame(
            rows,
            dtypes={
                "deliveredAt": "string",
                "expiredAt": "string",
                "id": "string",
                "interface": "string",
                "messageType": "string",
                "readAt": "string",
                "recipient": "string",
                "sender": "string",
                "senderId": "string",
                "sentAt": "string",
            },
            order=[
                "deliveredAt",
                "expiredAt",
                "id",
                "interface",
                "messageType",
                "readAt",
                "recipient",
                "sender",
                "senderId",
                "sentAt",
            ],
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def callback(
        self,
        id,
        *,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
    ) -> pd.Series:
        """One callback record, by id, as a Series.

        Columns:
          active (boolean)
          api_version (Int64)
          id (string)
          invalid (boolean)
          receiver (object)
          receiver_type (string)
          type (string)
          url (string)
        """
        rec = self.sdk.Callback().load({"id": id})
        return to_series(
            rec,
            dtypes={
                "active": "boolean",
                "api_version": "Int64",
                "id": "string",
                "invalid": "boolean",
                "receiver": "object",
                "receiver_type": "string",
                "type": "string",
                "url": "string",
            },
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def contact(
        self,
        id,
        *,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
    ) -> pd.Series:
        """One contact record, by id, as a Series.

        Columns:
          birthday_date (string)
          city (string)
          collection (object, required)
          contact_expire_after (Int64, required)
          contacts_count (Int64, required)
          country (string)
          created_by (string, required)
          date_created (string, required)
          date_updated (string, required)
          description (string)
          email (string)
          first_name (string)
          gender (string, required)
          group_id (string)
          groups (object, required)
          id (string, required)
          idx (string)
          last_name (string)
          name (string, required)
          permissions (object)
          phone_number (string)
          read (boolean)
          send (boolean)
          size (Int64, required)
          … and 5 more (see README.md, or df.dtypes)
        """
        rec = self.sdk.Contact().load({"id": id})
        return to_series(
            rec,
            dtypes={
                "birthday_date": "string",
                "city": "string",
                "collection": "object",
                "contact_expire_after": "Int64",
                "contacts_count": "Int64",
                "country": "string",
                "created_by": "string",
                "date_created": "string",
                "date_updated": "string",
                "description": "string",
                "email": "string",
                "first_name": "string",
                "gender": "string",
                "group_id": "string",
                "groups": "object",
                "id": "string",
                "idx": "string",
                "last_name": "string",
                "name": "string",
                "permissions": "object",
                "phone_number": "string",
                "read": "boolean",
                "send": "boolean",
                "size": "Int64",
                "source": "string",
                "type": "string",
                "username": "string",
                "value": "string",
                "write": "boolean",
            },
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def group(
        self,
        id,
        *,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
    ) -> pd.Series:
        """One group record, by id, as a Series.

        Columns:
          contact_expire_after (Int64, required)
          contacts_count (Int64, required)
          created_by (string, required)
          date_created (string, required)
          date_updated (string, required)
          description (string, required)
          id (string, required)
          idx (string)
          name (string, required)
          permissions (object)
        """
        rec = self.sdk.Group().load({"id": id})
        return to_series(
            rec,
            dtypes={
                "contact_expire_after": "Int64",
                "contacts_count": "Int64",
                "created_by": "string",
                "date_created": "string",
                "date_updated": "string",
                "description": "string",
                "id": "string",
                "idx": "string",
                "name": "string",
                "permissions": "object",
            },
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def permission(
        self,
        id,
        *,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
    ) -> pd.Series:
        """One permission record, by id, as a Series.

        Columns:
          group_id (string, required)
          id (string)
          read (boolean, required)
          send (boolean, required)
          username (string, required)
          write (boolean, required)
        """
        rec = self.sdk.Permission().load({"id": id})
        return to_series(
            rec,
            dtypes={
                "group_id": "string",
                "id": "string",
                "read": "boolean",
                "send": "boolean",
                "username": "string",
                "write": "boolean",
            },
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def sendername(
        self,
        id,
        *,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
    ) -> pd.Series:
        """One sendername record, by id, as a Series.

        Columns:
          created_at (string)
          id (string)
          is_default (boolean)
          sender (string)
          status (string)
        """
        rec = self.sdk.Sendername().load({"id": id})
        return to_series(
            rec,
            dtypes={
                "created_at": "string",
                "id": "string",
                "is_default": "boolean",
                "sender": "string",
                "status": "string",
            },
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def short_url(
        self,
        id,
        *,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
    ) -> pd.Series:
        """One short_url record, by id, as a Series.

        Columns:
          description (string)
          expire (string)
          filename (string)
          hits (Int64)
          hits_unique (Int64)
          id (string)
          name (string)
          short_url (string)
          type (string)
          url (string)
        """
        rec = self.sdk.ShortUrl().load({"id": id})
        return to_series(
            rec,
            dtypes={
                "description": "string",
                "expire": "string",
                "filename": "string",
                "hits": "Int64",
                "hits_unique": "Int64",
                "id": "string",
                "name": "string",
                "short_url": "string",
                "type": "string",
                "url": "string",
            },
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def subuser(
        self,
        id,
        *,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
    ) -> pd.Series:
        """One subuser record, by id, as a Series.

        Columns:
          active (boolean)
          credentials (object, required)
          description (string)
          id (string)
          points (object)
          username (string)
        """
        rec = self.sdk.Subuser().load({"id": id})
        return to_series(
            rec,
            dtypes={
                "active": "boolean",
                "credentials": "object",
                "description": "string",
                "id": "string",
                "points": "object",
                "username": "string",
            },
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )

    def template(
        self,
        id,
        *,
        flatten=FLATTEN_DEFAULT,
        dtype: bool = True,
        parse_dates=None,
    ) -> pd.Series:
        """One template record, by id, as a Series.

        Columns:
          id (string)
          name (string)
          normalize (boolean)
          template (string)
        """
        rec = self.sdk.Template().load({"id": id})
        return to_series(
            rec,
            dtypes={
                "id": "string",
                "name": "string",
                "normalize": "boolean",
                "template": "string",
            },
            flatten=flatten,
            dtype=dtype,
            parse_dates=parse_dates,
        )
