(* Smsapi SDK client (generated by @voxgig/sdkgen).
 *
 * The SDK "object" is the runtime sdk_client record (see Sdk_types). These
 * constructors wire the embedded config + feature factory (Sdk_config) into
 * the API-agnostic client builders (Sdk_features.make_client_base / sdk_test).
 * Entity accessors return an entity_obj whose CRUD closures run the pipeline. *)

open Voxgig_struct
open Sdk_types
open Sdk_features

(* Construct a live client from options (Noval for defaults). *)
let make (options : value) : sdk_client =
  make_client_base
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    options

(* No-argument convenience constructor. *)
let make0 () : sdk_client = make Noval

(* Construct a client in test mode (in-memory mock transport). *)
let test () : sdk_client =
  sdk_test
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    Noval Noval

(* Test-mode client with explicit test / sdk options. *)
let test_with (testopts : value) (sdkopts : value) : sdk_client =
  sdk_test
    ~config:(Sdk_config.make_config ())
    ~make_feature:Sdk_config.make_feature
    testopts sdkopts

(* Low-level escape hatches (raw transport call / request preparation). *)
let direct (client : sdk_client) (fetchargs : value) : value =
  Sdk_features.direct client fetchargs

let graphql (client : sdk_client) (query : string) (variables : value)
    (ctrl : value) : value =
  Sdk_features.graphql client query variables ctrl

let prepare (client : sdk_client) (fetchargs : value) : value =
  Sdk_features.prepare client fetchargs

(* Available entity bound to a client:  available client entopts *)
let available (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_available.make client entopts

(* Blacklist entity bound to a client:  blacklist client entopts *)
let blacklist (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_blacklist.make client entopts

(* Callback entity bound to a client:  callback client entopts *)
let callback (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_callback.make client entopts

(* Contact entity bound to a client:  contact client entopts *)
let contact (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_contact.make client entopts

(* ContactsField entity bound to a client:  contacts_field client entopts *)
let contacts_field (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_contacts_field.make client entopts

(* ContactsFieldOption entity bound to a client:  contacts_field_option client entopts *)
let contacts_field_option (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_contacts_field_option.make client entopts

(* Contactsgroup entity bound to a client:  contactsgroup client entopts *)
let contactsgroup (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_contactsgroup.make client entopts

(* Contactstrash entity bound to a client:  contactstrash client entopts *)
let contactstrash (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_contactstrash.make client entopts

(* FieldAvailable entity bound to a client:  field_available client entopts *)
let field_available (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_field_available.make client entopts

(* Group entity bound to a client:  group client entopts *)
let group (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_group.make client entopts

(* MfaCode entity bound to a client:  mfa_code client entopts *)
let mfa_code (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_mfa_code.make client entopts

(* OptOut entity bound to a client:  opt_out client entopts *)
let opt_out (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_opt_out.make client entopts

(* OptOutSetting entity bound to a client:  opt_out_setting client entopts *)
let opt_out_setting (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_opt_out_setting.make client entopts

(* Permission entity bound to a client:  permission client entopts *)
let permission (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_permission.make client entopts

(* Ping entity bound to a client:  ping client entopts *)
let ping (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_ping.make client entopts

(* Profile entity bound to a client:  profile client entopts *)
let profile (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_profile.make client entopts

(* Rcs entity bound to a client:  rcs client entopts *)
let rcs (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_rcs.make client entopts

(* Sendername entity bound to a client:  sendername client entopts *)
let sendername (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_sendername.make client entopts

(* SendernameStatement entity bound to a client:  sendername_statement client entopts *)
let sendername_statement (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_sendername_statement.make client entopts

(* SentRcsMessage entity bound to a client:  sent_rcs_message client entopts *)
let sent_rcs_message (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_sent_rcs_message.make client entopts

(* ShipmentCountryVolume entity bound to a client:  shipment_country_volume client entopts *)
let shipment_country_volume (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_shipment_country_volume.make client entopts

(* ShortUrl entity bound to a client:  short_url client entopts *)
let short_url (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_short_url.make client entopts

(* Smsdo entity bound to a client:  smsdo client entopts *)
let smsdo (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_smsdo.make client entopts

(* Smssendername entity bound to a client:  smssendername client entopts *)
let smssendername (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_smssendername.make client entopts

(* Smstemplate entity bound to a client:  smstemplate client entopts *)
let smstemplate (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_smstemplate.make client entopts

(* Subuser entity bound to a client:  subuser client entopts *)
let subuser (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_subuser.make client entopts

(* Template entity bound to a client:  template client entopts *)
let template (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_template.make client entopts

(* UserRcsSenderCollection entity bound to a client:  user_rcs_sender_collection client entopts *)
let user_rcs_sender_collection (client : sdk_client) (entopts : value) : entity_obj =
  Sdk_entity_user_rcs_sender_collection.make client entopts

(* Entity by name (None for a name this SDK did not generate). *)
let entity (client : sdk_client) (name : string) (entopts : value) : entity_obj option =
  match name with
  | "available" -> Some (Sdk_entity_available.make client entopts)
  | "blacklist" -> Some (Sdk_entity_blacklist.make client entopts)
  | "callback" -> Some (Sdk_entity_callback.make client entopts)
  | "contact" -> Some (Sdk_entity_contact.make client entopts)
  | "contacts_field" -> Some (Sdk_entity_contacts_field.make client entopts)
  | "contacts_field_option" -> Some (Sdk_entity_contacts_field_option.make client entopts)
  | "contactsgroup" -> Some (Sdk_entity_contactsgroup.make client entopts)
  | "contactstrash" -> Some (Sdk_entity_contactstrash.make client entopts)
  | "field_available" -> Some (Sdk_entity_field_available.make client entopts)
  | "group" -> Some (Sdk_entity_group.make client entopts)
  | "mfa_code" -> Some (Sdk_entity_mfa_code.make client entopts)
  | "opt_out" -> Some (Sdk_entity_opt_out.make client entopts)
  | "opt_out_setting" -> Some (Sdk_entity_opt_out_setting.make client entopts)
  | "permission" -> Some (Sdk_entity_permission.make client entopts)
  | "ping" -> Some (Sdk_entity_ping.make client entopts)
  | "profile" -> Some (Sdk_entity_profile.make client entopts)
  | "rcs" -> Some (Sdk_entity_rcs.make client entopts)
  | "sendername" -> Some (Sdk_entity_sendername.make client entopts)
  | "sendername_statement" -> Some (Sdk_entity_sendername_statement.make client entopts)
  | "sent_rcs_message" -> Some (Sdk_entity_sent_rcs_message.make client entopts)
  | "shipment_country_volume" -> Some (Sdk_entity_shipment_country_volume.make client entopts)
  | "short_url" -> Some (Sdk_entity_short_url.make client entopts)
  | "smsdo" -> Some (Sdk_entity_smsdo.make client entopts)
  | "smssendername" -> Some (Sdk_entity_smssendername.make client entopts)
  | "smstemplate" -> Some (Sdk_entity_smstemplate.make client entopts)
  | "subuser" -> Some (Sdk_entity_subuser.make client entopts)
  | "template" -> Some (Sdk_entity_template.make client entopts)
  | "user_rcs_sender_collection" -> Some (Sdk_entity_user_rcs_sender_collection.make client entopts)
  | _ -> None
