<?php
declare(strict_types=1);

// Smsapi SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

SmsapiUtility::setRegistrar(function (SmsapiUtility $u): void {
    $u->clean = [SmsapiClean::class, 'call'];
    $u->clean_add = [SmsapiClean::class, 'add'];
    $u->clean_explain = [SmsapiDone::class, 'clean_explain'];
    $u->done = [SmsapiDone::class, 'call'];
    $u->make_error = [SmsapiMakeError::class, 'call'];
    $u->feature_add = [SmsapiFeatureAdd::class, 'call'];
    $u->feature_hook = [SmsapiFeatureHook::class, 'call'];
    $u->feature_init = [SmsapiFeatureInit::class, 'call'];
    $u->fetcher = [SmsapiFetcher::class, 'call'];
    $u->make_fetch_def = [SmsapiMakeFetchDef::class, 'call'];
    $u->make_context = [SmsapiMakeContext::class, 'call'];
    $u->make_options = [SmsapiMakeOptions::class, 'call'];
    $u->make_request = [SmsapiMakeRequest::class, 'call'];
    $u->make_response = [SmsapiMakeResponse::class, 'call'];
    $u->make_result = [SmsapiMakeResult::class, 'call'];
    $u->make_point = [SmsapiMakePoint::class, 'call'];
    $u->make_spec = [SmsapiMakeSpec::class, 'call'];
    $u->make_url = [SmsapiMakeUrl::class, 'call'];
    $u->param = [SmsapiParam::class, 'call'];
    $u->prepare_auth = [SmsapiPrepareAuth::class, 'call'];
    $u->prepare_body = [SmsapiPrepareBody::class, 'call'];
    $u->prepare_headers = [SmsapiPrepareHeaders::class, 'call'];
    $u->prepare_method = [SmsapiPrepareMethod::class, 'call'];
    $u->prepare_params = [SmsapiPrepareParams::class, 'call'];
    $u->prepare_path = [SmsapiPreparePath::class, 'call'];
    $u->prepare_query = [SmsapiPrepareQuery::class, 'call'];
    $u->graphql_body = [SmsapiGraphql::class, 'body'];
    $u->graphql_errors = [SmsapiGraphql::class, 'errors'];
    $u->result_basic = [SmsapiResultBasic::class, 'call'];
    $u->result_body = [SmsapiResultBody::class, 'call'];
    $u->result_headers = [SmsapiResultHeaders::class, 'call'];
    $u->transform_request = [SmsapiTransformRequest::class, 'call'];
    $u->transform_response = [SmsapiTransformResponse::class, 'call'];
});
