;; Smsapi SDK public API (generated by @voxgig/sdkgen).
(ns sdk.api
  (:require [sdk.client :as client]
            [sdk.entity.available :as e-available]
            [sdk.entity.blacklist :as e-blacklist]
            [sdk.entity.callback :as e-callback]
            [sdk.entity.contact :as e-contact]
            [sdk.entity.contacts_field :as e-contacts_field]
            [sdk.entity.contacts_field_option :as e-contacts_field_option]
            [sdk.entity.contactsgroup :as e-contactsgroup]
            [sdk.entity.contactstrash :as e-contactstrash]
            [sdk.entity.field_available :as e-field_available]
            [sdk.entity.group :as e-group]
            [sdk.entity.mfa_code :as e-mfa_code]
            [sdk.entity.opt_out :as e-opt_out]
            [sdk.entity.opt_out_setting :as e-opt_out_setting]
            [sdk.entity.permission :as e-permission]
            [sdk.entity.ping :as e-ping]
            [sdk.entity.profile :as e-profile]
            [sdk.entity.rcs :as e-rcs]
            [sdk.entity.sendername :as e-sendername]
            [sdk.entity.sendername_statement :as e-sendername_statement]
            [sdk.entity.sent_rcs_message :as e-sent_rcs_message]
            [sdk.entity.shipment_country_volume :as e-shipment_country_volume]
            [sdk.entity.short_url :as e-short_url]
            [sdk.entity.smsdo :as e-smsdo]
            [sdk.entity.smssendername :as e-smssendername]
            [sdk.entity.smstemplate :as e-smstemplate]
            [sdk.entity.subuser :as e-subuser]
            [sdk.entity.template :as e-template]
            [sdk.entity.user_rcs_sender_collection :as e-user_rcs_sender_collection]))

(def make-sdk client/make-sdk)
(def test-sdk client/test-sdk)
(def direct client/direct)
(def graphql client/graphql)
(def prepare client/prepare)
(def options-map client/options-map)

;; Available accessor: (available client data)
(defn available [client data] (e-available/make client data))

;; Blacklist accessor: (blacklist client data)
(defn blacklist [client data] (e-blacklist/make client data))

;; Callback accessor: (callback client data)
(defn callback [client data] (e-callback/make client data))

;; Contact accessor: (contact client data)
(defn contact [client data] (e-contact/make client data))

;; ContactsField accessor: (contacts_field client data)
(defn contacts_field [client data] (e-contacts_field/make client data))

;; ContactsFieldOption accessor: (contacts_field_option client data)
(defn contacts_field_option [client data] (e-contacts_field_option/make client data))

;; Contactsgroup accessor: (contactsgroup client data)
(defn contactsgroup [client data] (e-contactsgroup/make client data))

;; Contactstrash accessor: (contactstrash client data)
(defn contactstrash [client data] (e-contactstrash/make client data))

;; FieldAvailable accessor: (field_available client data)
(defn field_available [client data] (e-field_available/make client data))

;; Group accessor: (group client data)
(defn group [client data] (e-group/make client data))

;; MfaCode accessor: (mfa_code client data)
(defn mfa_code [client data] (e-mfa_code/make client data))

;; OptOut accessor: (opt_out client data)
(defn opt_out [client data] (e-opt_out/make client data))

;; OptOutSetting accessor: (opt_out_setting client data)
(defn opt_out_setting [client data] (e-opt_out_setting/make client data))

;; Permission accessor: (permission client data)
(defn permission [client data] (e-permission/make client data))

;; Ping accessor: (ping client data)
(defn ping [client data] (e-ping/make client data))

;; Profile accessor: (profile client data)
(defn profile [client data] (e-profile/make client data))

;; Rcs accessor: (rcs client data)
(defn rcs [client data] (e-rcs/make client data))

;; Sendername accessor: (sendername client data)
(defn sendername [client data] (e-sendername/make client data))

;; SendernameStatement accessor: (sendername_statement client data)
(defn sendername_statement [client data] (e-sendername_statement/make client data))

;; SentRcsMessage accessor: (sent_rcs_message client data)
(defn sent_rcs_message [client data] (e-sent_rcs_message/make client data))

;; ShipmentCountryVolume accessor: (shipment_country_volume client data)
(defn shipment_country_volume [client data] (e-shipment_country_volume/make client data))

;; ShortUrl accessor: (short_url client data)
(defn short_url [client data] (e-short_url/make client data))

;; Smsdo accessor: (smsdo client data)
(defn smsdo [client data] (e-smsdo/make client data))

;; Smssendername accessor: (smssendername client data)
(defn smssendername [client data] (e-smssendername/make client data))

;; Smstemplate accessor: (smstemplate client data)
(defn smstemplate [client data] (e-smstemplate/make client data))

;; Subuser accessor: (subuser client data)
(defn subuser [client data] (e-subuser/make client data))

;; Template accessor: (template client data)
(defn template [client data] (e-template/make client data))

;; UserRcsSenderCollection accessor: (user_rcs_sender_collection client data)
(defn user_rcs_sender_collection [client data] (e-user_rcs_sender_collection/make client data))
